### ISSUE TITLE
feat: sort the versions before listing them

### ISSUE THREAD

**Issue by surli** [aubincleme/xtool#20]
Calling list versions currently doesn't sort the version, or does not use semver order to sort them.
e.g. right now I get something such as:

```
10.11.2
9.11.8
10.11.3
11.1
9.9
11.0
10.10
10.9
11.0.3
8.4.6
5.4.5
11.2
10.11.5
10.11.6
9.8.1
11.3-rc-1
11.3
11.4
11.3.1
10.11.8
11.6-SNAPSHOT
11.5
10.11.9
11.6-rc-1
11.3.2
11.6
8.4.4
10.11
11.6.1
11.3.3
11.7
11.8
```

**Comment by aubincleme** [comment]
Wow ; neat !

**Comment by aubincleme** [comment]
I'll see what I can do

**Comment by aubincleme** [comment]
@surli Versions / Instances should be automatically sorted at next save (new instance or new version). Don't hesitate to re-open if you have any issue.
