### ISSUE TITLE
feat: define a configuration for xtool

### ISSUE THREAD

**Issue by surli** [aubincleme/xtool#24]
I'd like to be able to always have some options enabled in my xtool command, but I don't want to type them each time.
For example, would be nice for me to always start my instances on debug. And I always forgot to type `--debug`.
It would be nice to be able to define a JSON file or any other format with some preferences for the commands.

**Comment by aubincleme** [comment]
@surli AFAIR, you already have this implemented as part of #15 .

To see the configuration being used currently : `x config debug`

To change the configuration : `x config debug -s true`

**Comment by surli** [comment]
Hm right, looks like we'd need some doc :p
