### ISSUE TITLE
bug: instances JSON is not properly synchronized in case of multiple operations

### ISSUE THREAD

**Issue by surli** [aubincleme/xtool#29]
Reproduction steps:
  - Create a new instance which involves to download a new version
  - while the version is downloading, in another console, perform a deletion of an existing instance named "Foo" 
  - after the new instance has been created, try to create a new instance called Foo

Expected result:
  - The new instance is properly created

Obtained result:
  - Got a message saying that instance Foo already exist. When trying to delete it again, it says that the directory for the instance does not exist. 

The workaround here, is to edit afterwards the JSON to remove manually the delete instance from it. I suspect that the map of instance is kept when the new version is downloading and it's then written back, without taking into account the changes that might have occured during the downloading.

**Comment by aubincleme** [comment]
Fixed in f191308
