### ISSUE TITLE
Allow to delete a versions

### ISSUE THREAD

**Issue by surli** [aubincleme/xtool#31]
#4 allows to download a snapshot but we currently cannot refresh it (would be done in #10), so it would be nice to be able to delete properly a version. 
So I could delete the snapshot version and download it back.

**Comment by aubincleme** [comment]
Added `x version prune` to delete every unused version in 7b4337f

**Comment by aubincleme** [comment]
Also added a new command `x version remove <version>` to remove a version ; youhoouuuu

**Comment by aubincleme** [comment]
One note : currently there's no check whatsoever on the removal of the version, beware if you are using linked instances.
