### ISSUE TITLE
feature request: Allow to download snapshot versions

### ISSUE THREAD

**Issue by surli** [aubincleme/xtool#4]
Would be great to be able to create an instance from a snapshot version.

**Comment by surli** [comment]
@aubincleme so this one can be closed?

**Comment by aubincleme** [comment]
Ha not yet, it's a WIP ; let me see if I can finish the feature in a timely manner.

**Comment by aubincleme** [comment]
Ok, I have something working. It might need a bit of refactoring and won't work for versions with XWiki Enterprise, but it's functional for current versions.

**Comment by aubincleme** [comment]
There you go, enjoy @surli :) 
(not closing the issue for now, I'd like to clean up a bit before closing)
